main:
	dot -Tsvg -O x86-cc-stack-64.dot
	dot -Tsvg -O x86-cc-esp-64.dot
	dot -Tsvg -O x86-cc-regs-64.dot
	dot -Tpng -O x86-cc-stack-64.dot
	dot -Tpng -O x86-cc-esp-64.dot
	dot -Tpng -O x86-cc-regs-64.dot
